### ISSUE TITLE
Add support for OPUS codec

### ISSUE THREAD

**Issue by Wohlstand** [coelckers/ZMusic#15]
Hello!

Recently, my buddy has noticed that GZDoom lacks OPUS support. Now I think, why not provide the supports for it also?

**What materials I have:**
- you need to add two libraries as external dependencies: `libopus` and `libopusfile`
- the API of `libopusfile` is similar to `libvorbisfile`. The difference is in call names, and in absence of sample rate related parameters and calls: OPUS has the fixed 48000 sample rate, it doesn't support any other.
- If you need the simple build, I developed my own CMake build for both libopus and libopusfile which you can find here:
  - https://github.com/WohlSoft/AudioCodecs/tree/master/libopus
  - https://github.com/WohlSoft/AudioCodecs/tree/master/libopusfile
- Here is an example of how to use libopusfile to play OPUS files: https://github.com/WohlSoft/SDL-Mixer-X/blob/master/src/codecs/music_opus.c

**Comment by coelckers** [comment]
libsndfile's latest release appears to support Opus already so if all goes well a simple update should suffice.

**Comment by Wohlstand** [comment]
Okay, I had to write this to my buddy, let him verify this... Thanks for the info! :fox_face:
