### ISSUE TITLE
should it be cmake . --build or cmake --build . ?

### ISSUE THREAD

**Issue by addeps3** [coelckers/ZMusic#29]
Hi, cmake wouldnt approve the first-mentioned syntax, so I tested switching the arguments around and it worked fine. 

Should the instructions be corrected? 

/Greetings, A.J

**Comment by alexey-lysiuk** [comment]
According to [this page](https://cmake.org/cmake/help/latest/manual/cmake.1.html), directory should be the last argument for both CMake invocations.

**Comment by addeps3** [comment]
Saw that you updated the instructions. 

Great! 
Have a nice Sunday evening! /A.J
