### ISSUE TITLE
Missing releases

### ISSUE THREAD

**Issue by jhonny-oliveira** [coelckers/ZMusic#30]
Hi!

It seems the latest releases went missing (release tab), could you please recreate them ? At least the last one, and then keep on updating it from there.

Thank you!
Jhonny Oliveira
https://xtradeb.net

**Comment by coelckers** [comment]
Let's close this.
ZMusic does not have the concept of a "release". Tags are made when a new commit gets used for a new GZDoom or Raze release. So most of the time the most recent tag would be the right thing, but if there's some fix in master, use that.

**Comment by jhonny-oliveira** [comment]
I agree! Thank you!
