### ISSUE TITLE
Add `find_library` for GME library.

### ISSUE THREAD

**Issue by ericonr** [coelckers/ZMusic#9]
Hi! I'm looking into packaging ZMusic for Void Linux, now that GZDoom depends on it. There is support for linking a system GME, but I couldn't find how to force it. I ended up patching out the internal gme stuff, and passing `-DGME_INCLUDE_DIR=/usr/include -DGME_LIBRARIES=gme` when running `cmake`. Is there a better way?

I noticed `zlib` had ` find_library( zlilb )`, but `gme` didn't.

Thanks!

**Comment by coelckers** [comment]
This is entirely by design because the version we use is not identical with the official one. There were some issues with some song formats not looping properly but it looks like this got deliberatly broken upstream. But it's an issue we do not want, so this was intentionally blocked.

**Comment by ericonr** [comment]
Oh, should it be removed from the CMake file, then? I might have been poking too much, but it would be good to know that a system gme isn't recommended at all. The option could even be removed from there, I think.
